USE BookBank;

INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2246,'Krajan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (383,'Ganxi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9012,'Gaza',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4120,'Budagovo',NULL,'665236');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1942,'Tagiura',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7997,'Agualote',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2040,'Lingda',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3110,'Qingkou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5395,'Dū Qal‘ah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4886,'Mallow',NULL,'P51');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1240,'Kyustendil',NULL,'2599');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1696,'Gambarjati',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6213,'Memphis','Tennessee','38197');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9981,'Cambará',NULL,'86390-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2729,'Las Palmas','Oaxaca','71984');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9437,'La Cruz de Río Grande',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1552,'Shijak',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3539,'Jobabo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6455,'Areeiro','Portalegre','7300-440');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6042,'Incheon',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (10,'Jabinyānah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4079,'Stockholm','Stockholm','111 61');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1121,'Pingkai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9157,'Dongba',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7403,'Dadiharja',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1493,'União da Vitória',NULL,'84600-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5886,'Xuedian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2730,'Portland','Oregon','97296');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1924,'Pécs','Baranya','7610');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2090,'Beskolen',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8234,'Burgersdorp',NULL,'9744');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9733,'Deventer','Provincie Overijssel','7409');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4790,'Sebeta',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9651,'Río Tercero',NULL,'5850');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5391,'Tuchola',NULL,'89-501');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5008,'Ipoh','Perak','30506');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5205,'Bangkal',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5699,'Moreira de Geraz do Lima','Viana do Castelo','4905-266');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (209,'Bāsht',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (529,'Hexia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5380,'Belo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1481,'Azul',NULL,'7300');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8454,'Acao',NULL,'1116');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2756,'Chroustovice',NULL,'538 63');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6460,'Caxito',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6612,'Novki',NULL,'601340');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4150,'Djambala',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4379,'Chengyang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7800,'Pasaje',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5544,'Dolod',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7310,'Nong Yai',NULL,'20190');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9529,'Apeldoorn','Provincie Gelderland','7329');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5032,'Qinshan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8075,'Lundazi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9873,'Reims','Champagne-Ardenne','51679 CEDEX 2');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4630,'Marulanda',NULL,'173007');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (725,'Undurkhaan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1332,'Xianning',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8601,'Jabon',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2161,'Comagascas',NULL,'1950');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9591,'Xukou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7335,'La Esperanza',NULL,'546058');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9320,'Beyla',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2287,'Muhos',NULL,'91501');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6173,'Sukarame',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5957,'Odeleite','Faro','8950-355');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4823,'Yur’yevets',NULL,'155450');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5506,'Nan’ao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3108,'Ehen Hudag',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6172,'Wonokerto',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9651,'Río Tercero',NULL,'5850');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2479,'Spanish Wells',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4580,'Karasuk',NULL,'632868');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9472,'Tiantai Chengguanzhen',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4786,'Rakhmanovo',NULL,'142145');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6148,'Kondrovo',NULL,'422102');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5188,'Zárate',NULL,'3423');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7208,'Spring','Texas','77386');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4560,'Ngujuran',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1393,'Visconde do Rio Branco',NULL,'36520-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9746,'Zhangfeng',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9413,'Karachi',NULL,'12311');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2425,'Krajan Rowokangkung',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9085,'Lingkou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1874,'Chinju',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8115,'Daga',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9839,'Ronov nad Doubravou',NULL,'538 42');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8970,'Shanghuang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5699,'Moreira de Geraz do Lima','Viana do Castelo','4905-266');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5599,'Karlshamn','Blekinge','374 81');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9282,'Yacuiba',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4821,'Moss','Ostfold','1531');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5295,'Nyrkiv',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3812,'Jarigue',NULL,'9407');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4192,'Skrunda',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9103,'Kamenjane',NULL,'1221');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5461,'Foumbot',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5299,'Sadabe',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4084,'Youkaichi',NULL,'958-0052');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9264,'Rio Claro',NULL,'13500-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1254,'Qingu',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5416,'Perechyn',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2581,'Nikolayevka',NULL,'430901');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9757,'Gelsenkirchen','Nordrhein-Westfalen','45886');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4496,'Vitebsk',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5439,'Sukamulia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7620,'Jiubao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (979,'Mapusagafou',NULL,'96799');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9680,'Newark','New Jersey','07112');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8435,'Mirovka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4040,'Daji',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3570,'Pueai Noi',NULL,'40340');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8100,'Daying',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (960,'Lazaro Cardenas','Guerrero','40160');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3710,'Olsztyn',NULL,'42-256');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7683,'Studénka',NULL,'742 13');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9242,'Tubod',NULL,'9209');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8260,'Junín',NULL,'5281');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3708,'Erandique',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7276,'Bandar-e Māhshahr',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3332,'Usulután',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8132,'Taisen-ri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (31,'Bulung’ur',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (632,'Matamey',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1948,'Maromme','Haute-Normandie','76152 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (103,'Quimper','Bretagne','29563 CEDEX 9');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6589,'Baojia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6907,'Itaquyry',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7985,'Ágios Efstrátios',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3158,'Maopingchang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4386,'Ilo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (178,'Bancroft','Ontario','S4X');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4619,'Chumphon',NULL,'30440');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3320,'Paço','Viana do Castelo','4910-060');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5132,'Qiankou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7156,'Ta’ Xbiex',NULL,'ZTN');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2627,'Dongfeng',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2754,'Ciudad Bolivia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1308,'Vyritsa',NULL,'188382');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1988,'Dokuchayevs’k',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4379,'Chengyang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2869,'Tarrafal',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (454,'Patpata Segundo',NULL,'3604');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (383,'Ribeirão Pires',NULL,'09400-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8698,'Huatajata',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (832,'Gualeguay',NULL,'2840');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8191,'Jasugih Selatan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (737,'Pilar',NULL,'8420');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2769,'Bulbul',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6557,'Bahāwalnagar',NULL,'57031');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7403,'Dadiharja',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8668,'Saint Louis','Missouri','63180');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (857,'Mahdishahr',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4180,'Victoria',NULL,'6406');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3824,'Cankova',NULL,'9261');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3108,'Ehen Hudag',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9301,'Pećigrad',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9107,'Przyborów',NULL,'80-867');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4239,'Ust-Maya',NULL,'678620');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9646,'Gândara','Viseu','3450-405');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8133,'Sufang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3822,'Barg-e Matāl',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (832,'Gualeguay',NULL,'2840');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1608,'Nossa Senhora do Socorro',NULL,'49160-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9628,'Ponte','Viseu','3680-191');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9730,'Subaykhān',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9729,'Tavira','Faro','8800-303');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6074,'Horqueta',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2603,'Mancilang',NULL,'1219');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3597,'Atakpamé',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7577,'Žacléř',NULL,'542 01');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3522,'Bacabal',NULL,'65700-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6890,'Uvarovo',NULL,'393479');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7236,'Onoda',NULL,'979-1543');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1564,'Novokhovrino',NULL,'141707');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (212,'Dipayal',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6311,'Ţawr al Bāḩah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6160,'Bočar',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1893,'Queluz de Baixo','Lisboa','2730-015');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9445,'Palaiseau','Île-de-France','91124 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1159,'Heung-hai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4379,'Chengyang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5926,'Ressano Garcia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6584,'Barapas',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4823,'Yur’yevets',NULL,'155450');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8692,'Katovice',NULL,'387 11');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3288,'Shijing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6760,'Tunduma',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7709,'Paris 15','Île-de-France','75729 CEDEX 15');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5215,'Pombal','Braga','4850-304');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3544,'Tōno',NULL,'326-0036');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (758,'Inglewood','California','90305');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4609,'Oltinko’l',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4750,'Hinunangan',NULL,'6608');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8484,'Bouctouche','Nouveau-Brunswick','E4S');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5535,'Korçë',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9788,'Wakkanai',NULL,'763-0231');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4084,'Youkaichi',NULL,'958-0052');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1065,'Roanoke','Virginia','24040');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4041,'Włoszczowa',NULL,'29-100');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2176,'Dapaong',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4148,'Miyakonojō',NULL,'889-1912');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7506,'South Tangerang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9120,'Gulonggang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9280,'Jiangxi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1583,'Shuangqiao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9102,'San Isidro','Nuevo Leon','64103');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4201,'Sviblovo',NULL,'607224');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3072,'Bentar Girang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9990,'Qiaozhuang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1942,'Tagiura',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6035,'Piraquara',NULL,'83300-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4515,'Kaliuling',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5860,'Delgado',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (566,'Pasirsongket Dua',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8413,'Selajambe Satu',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (131,'Igurusi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7875,'Chocz',NULL,'63-313');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4454,'Villach','Kaernten','9580');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2287,'Muhos',NULL,'91501');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4244,'New Washington',NULL,'5610');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5541,'Vale de Touros','Setúbal','2950-137');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9472,'Tiantai Chengguanzhen',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4562,'Xiaolou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9855,'Panalingaan',NULL,'9610');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (512,'Bangluo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8423,'Klagen',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8492,'Goczałkowice Zdrój',NULL,'43-503');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (272,'Libacao',NULL,'5602');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4343,'Carnaxide','Lisboa','2790-009');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8396,'Paris 13','Île-de-France','75638 CEDEX 13');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7007,'Višňova',NULL,'464 01');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2185,'Shiraoi',NULL,'455-0054');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9427,'Zlatni Pyasatsi',NULL,'9194');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (671,'Fastiv',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5625,'Babica',NULL,'38-115');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8901,'Wuku',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8239,'Tost',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5363,'Weishan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2367,'Jinping',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7031,'‘Afak',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8638,'Burgkirchen','Oberösterreich','5271');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5295,'Nyrkiv',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3635,'Famatina',NULL,'4203');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3344,'Energeticheskiy',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9165,'Berbek',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4509,'Kriel',NULL,'2276');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5259,'Lazarevac',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8273,'Ra-ngae',NULL,'96130');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (301,'Jianba',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8452,'Daga',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4886,'Mallow',NULL,'P51');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3659,'Martigues','Provence-Alpes-Côte d''Azur','13503 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9451,'Daxing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9076,'Shapaja',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8239,'Tost',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6324,'Wujian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8820,'Abricots',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1633,'Bayambang',NULL,'2423');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2229,'Shijing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7772,'Gandu',NULL,'45450-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5586,'Kofelē',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5500,'Kenyau',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6400,'Nansan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4148,'Miyakonojō',NULL,'889-1912');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5032,'Qinshan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9057,'Kebonkaret',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4047,'Tupanciretã',NULL,'98170-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7547,'Muonio',NULL,'99301');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4886,'Senj',NULL,'53270');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9720,'Al Burayqah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9599,'Charleville-Mézières','Champagne-Ardenne','08107 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4838,'Přimda',NULL,'348 06');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9085,'Lingkou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9646,'Gândara','Viseu','3450-405');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2614,'Santa María Ixhuatán',NULL,'06010');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4484,'Piritiba',NULL,'44830-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4209,'Umag',NULL,'52470');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9762,'Oyabe',NULL,'932-0056');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9715,'Sawin',NULL,'22-107');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (856,'Sanming',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9767,'Kasungu',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9729,'Tavira','Faro','8800-303');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3943,'Ballybofey',NULL,'V23');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9425,'Tianjin',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1967,'Majan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5138,'Dębowa Łąka',NULL,'87-207');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8115,'Daga',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4560,'Ngujuran',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8808,'Jablah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6136,'Mboursou Léré',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2813,'Pendembu',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4750,'Hinunangan',NULL,'6608');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (983,'Gutian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9757,'Gelsenkirchen','Nordrhein-Westfalen','45886');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (841,'Gotputuk',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3320,'Paço','Viana do Castelo','4910-060');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1159,'Heung-hai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (189,'Haguenau','Alsace','67504 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1541,'Phatthana Nikhom',NULL,'53230');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3199,'Staraya Ladoga',NULL,'187412');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8051,'Corralillo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2163,'Sut-Khol’',NULL,'668150');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4475,'Guang’an',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4886,'Mallow',NULL,'P51');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3669,'De la Paz',NULL,'7105');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7094,'Ketian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2672,'Svetlogorsk',NULL,'663214');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2559,'Mafeng',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9591,'Xukou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8448,'Konary',NULL,'63-910');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9733,'Deventer','Provincie Overijssel','7409');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9043,'Abovyan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3851,'Yangi-Nishon Shahri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7895,'As Saffānīyah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (551,'Purificación',NULL,'734509');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4509,'Kriel',NULL,'2276');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2763,'Sankui',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2393,'Xo’jayli Shahri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8970,'Shanghuang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4458,'Kalapagada',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (967,'Andalucía',NULL,'763008');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3710,'Olsztyn',NULL,'42-256');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4924,'Rustam jo Goth',NULL,'78051');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3695,'Anopog',NULL,'1695');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8896,'Modakeke',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8698,'Huatajata',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9562,'Puerto Quellón',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7468,'Gaoliang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1117,'Krajan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1019,'Rantau',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7577,'Žacléř',NULL,'542 01');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7236,'Onoda',NULL,'979-1543');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5706,'Maofan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2766,'Kota Ternate',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9134,'Magan',NULL,'677904');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8859,'Caxambu',NULL,'37440-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2452,'Koryukivka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3708,'Erandique',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1715,'Duodaoshi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9587,'Nangkasari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9165,'Berbek',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3303,'Sriwing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8795,'Longsheng',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1964,'Jinta',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3326,'Linköping','Östergötland','582 31');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6368,'Plettenberg Bay',NULL,'6606');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6917,'María la Baja',NULL,'131077');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3821,'Dadapan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7208,'Spring','Texas','77386');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2367,'Jinping',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3944,'Austin','Texas','78715');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8199,'Avon','Île-de-France','77214 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4656,'Cabouco','Ilha de São Miguel','9560-305');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2291,'Virginia',NULL,'D18');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (714,'Pétionville',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9165,'Berbek',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4044,'Vitanje',NULL,'3205');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4800,'Agustín Codazzi',NULL,'202058');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5906,'Wangcungang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5731,'Concepción',NULL,'07023');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4484,'Piritiba',NULL,'44830-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5048,'Vrakháti',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3132,'Boroon',NULL,'9201');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7260,'Taphan Hin',NULL,'66110');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1545,'Velika',NULL,'34330');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2422,'Bantul',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7899,'Tyringe','Skåne','282 91');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2399,'Fenghuang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4475,'Huoshaoping',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1009,'Montelíbano',NULL,'234008');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5729,'Sendang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9658,'Yelyzavethradka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9729,'Tavira','Faro','8800-303');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8627,'Kultuk',NULL,'665911');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9375,'Ntungamo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5439,'Sukamulia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2705,'Dongshan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9603,'Luis Donaldo Colosio','Coahuila De Zaragoza','26095');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5181,'Tamansari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6368,'Plettenberg Bay',NULL,'6606');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4150,'Djambala',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4281,'Zhongpai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8075,'Lundazi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7017,'Maevatanana',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6448,'Ban Selaphum',NULL,'51130');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1778,'Krasnoye',NULL,'652577');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3522,'Bacabal',NULL,'65700-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3967,'Orsay','Île-de-France','91851 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4810,'San José de las Lajas',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1715,'Duodaoshi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4272,'Alingsås','Västra Götaland','441 28');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3143,'Sihai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3851,'Yangi-Nishon Shahri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5712,'Torino','Piemonte','10152');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (788,'Paleran',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5677,'Vaitogi',NULL,'96799');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1541,'Phatthana Nikhom',NULL,'53230');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8568,'Bakov nad Jizerou',NULL,'294 01');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4116,'Thaton',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2388,'Richmond','Virginia','23289');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8928,'Gedongmulyo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7064,'Al Maḩwīt',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8538,'Liushan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1988,'Dokuchayevs’k',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1193,'Lancai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3708,'Erandique',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1493,'União da Vitória',NULL,'84600-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2103,'Laxou','Lorraine','54529 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7577,'Žacléř',NULL,'542 01');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1549,'Prata',NULL,'58550-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3616,'Bartolomé Masó',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8383,'Quinta','Braga','4860-077');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1948,'Maromme','Haute-Normandie','76152 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (775,'Gaigeturi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5363,'Weishan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4539,'Concepción',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5652,'Orange','Provence-Alpes-Côte d''Azur','84104 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6496,'San Rafael',NULL,'5039');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4967,'Myeik',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1866,'Rudolfov',NULL,'373 71');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5436,'Itaperuçu',NULL,'83560-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2192,'Lamarosa','Coimbra','3025-389');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7959,'La Molina',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4150,'Djambala',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9680,'Newark','New Jersey','07112');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5699,'Moreira de Geraz do Lima','Viana do Castelo','4905-266');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6485,'Pampas Chico',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2291,'Virginia',NULL,'D18');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3710,'Olsztyn',NULL,'42-256');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8273,'Ra-ngae',NULL,'96130');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6133,'Yongtai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7895,'As Saffānīyah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4455,'Quintong',NULL,'2417');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4281,'Zhongpai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8396,'Paris 13','Île-de-France','75638 CEDEX 13');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4886,'Senj',NULL,'53270');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6082,'Makrychóri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5871,'Lwówek Śląski',NULL,'59-601');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5087,'Qijing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4869,'Kiruru',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5806,'Dapdapan',NULL,'5806');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9242,'Tubod',NULL,'9209');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1117,'Krajan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6436,'Hetou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9085,'Lingkou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (27,'Qinhe',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1474,'Pawitan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (47,'Albanel','Québec','G8M');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6299,'Ténenkou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1481,'Azul',NULL,'7300');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3110,'Qingkou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6496,'San Rafael',NULL,'5039');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5596,'Hushan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2866,'Kuantan','Pahang','26040');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8928,'Gedongmulyo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5130,'Malabang',NULL,'9300');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7301,'Yongtai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8979,'Toumodi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5544,'Dolod',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4041,'Włoszczowa',NULL,'29-100');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5436,'Itaperuçu',NULL,'83560-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (44,'Ancona','Marche','60129');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6781,'Cibulakan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9626,'Araras',NULL,'13600-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4420,'Jājarm',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4076,'Ilhabela',NULL,'11630-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7208,'Spring','Texas','77386');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6698,'Zhanjiang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7017,'Maevatanana',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6917,'María la Baja',NULL,'131077');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6286,'Shiniujiang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7558,'Lyon','Rhône-Alpes','69239 CEDEX 02');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3943,'Ballybofey',NULL,'V23');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2909,'Kebonan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7895,'As Saffānīyah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1114,'Kampong Thom',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4148,'Miyakonojō',NULL,'889-1912');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7800,'Pasaje',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5731,'Concepción',NULL,'07023');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8161,'Huaitu',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4185,'Shibīn al Kawm',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (510,'Tangxing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1302,'Abades','Santarém','2435-225');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1254,'Kołbiel',NULL,'05-340');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3522,'Mosrentgen',NULL,'391237');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9972,'Juhaynah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5744,'Guaitarilla',NULL,'525508');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8553,'Salam',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3357,'Eskifjörður',NULL,'735');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9545,'Kieta',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8962,'Pinggirsari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2422,'Bantul',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6042,'Fengtai Chengguanzhen',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8199,'Wissous','Île-de-France','91324 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (910,'Longquan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4756,'Skýros',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7002,'Mweka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6228,'Akouda',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3249,'Puncakmanis',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7335,'La Esperanza',NULL,'546058');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3320,'Paço','Viana do Castelo','4910-060');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1065,'Roanoke','Virginia','24040');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6436,'Hetou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5794,'Trilj',NULL,'21240');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8692,'Katovice',NULL,'387 11');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (512,'Bangluo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2414,'Ivanteyevka',NULL,'142139');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (510,'Tangxing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7653,'København','Region Hovedstaden','1666');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5652,'Orange','Provence-Alpes-Côte d''Azur','84104 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6368,'Plettenberg Bay',NULL,'6606');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9353,'Saraburi',NULL,'18190');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9601,'Xilópolis',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4040,'Daji',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9587,'Nangkasari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9880,'Milín',NULL,'261 01');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6801,'Koga',NULL,'869-0233');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9730,'Subaykhān',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4230,'Masaran',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3943,'Ballybofey',NULL,'V23');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4244,'New Washington',NULL,'5610');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5518,'Sacramento','California','95818');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7571,'Weibin',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9043,'Abovyan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4777,'Saskylakh',NULL,'187542');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6911,'Guangyuan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1713,'Sviblovo',NULL,'627603');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4192,'Skrunda',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7876,'Chuguyevka',NULL,'692607');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3739,'Muye',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3344,'Energeticheskiy',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (50,'Kil’mez’',NULL,'613570');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7082,'Bagansiapiapi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1935,'Zheleznodorozhnyy',NULL,'238411');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3035,'Aylmer','Ontario','N5H');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (383,'Ribeirão Pires',NULL,'09400-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5569,'Seixo de Manhoses','Bragança','5360-185');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4523,'Pingdi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2287,'Muhos',NULL,'91501');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (967,'Andalucía',NULL,'763008');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1893,'Queluz de Baixo','Lisboa','2730-015');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8342,'Hauhena',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5724,'Huangtugang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6617,'Duyang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9242,'Tubod',NULL,'9209');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1552,'Shijak',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4843,'Hamburg','Hamburg','22041');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (47,'Albanel','Québec','G8M');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2341,'Helsingborg','Skåne','251 08');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8047,'Lae',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5988,'San Diego','California','92105');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1649,'Lüyang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2509,'Chodová Planá',NULL,'348 15');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2581,'Nikolayevka',NULL,'430901');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2302,'Vityazevo',NULL,'353421');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7895,'As Saffānīyah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2697,'Kiuola',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1254,'Kołbiel',NULL,'05-340');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3578,'Xazgat',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9591,'Xukou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3708,'Erandique',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8599,'San Pedro Necta',NULL,'13006');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1031,'Pecka',NULL,'507 82');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4041,'Włoszczowa',NULL,'29-100');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6382,'Biqiao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4560,'Ngujuran',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6393,'Baabda',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7884,'Vide','Guarda','6285-105');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7485,'Mabini',NULL,'6313');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (983,'Gutian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8448,'Konary',NULL,'63-910');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2131,'Plovdiv',NULL,'4000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (454,'Patpata Segundo',NULL,'3604');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6698,'Zhanjiang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2705,'Dongshan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9261,'Botou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8161,'Huaitu',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (95,'Kisai',NULL,'347-0105');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3901,'Amvrosiyivka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5181,'Tamansari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4682,'Jiangxigou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7772,'Gandu',NULL,'45450-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2103,'Laxou','Lorraine','54529 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6589,'Baojia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5666,'Sanlicheng',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9788,'Wakkanai',NULL,'763-0231');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7620,'Jiubao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1657,'Nankou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9813,'Sibaté',NULL,'111971');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1062,'‘Arīshah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5472,'Chãos','Braga','4830-813');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7033,'Darmasari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9085,'Lingkou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1592,'Saky',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1880,'Terenozek',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9143,'Parumasan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9994,'Danirai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5599,'Karlshamn','Blekinge','374 81');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1159,'Heung-hai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9626,'Araras',NULL,'13600-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (985,'Uppsala','Uppsala','752 42');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7653,'København','Region Hovedstaden','1666');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1114,'Kampong Thom',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8527,'Loa Janan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1008,'San Rafael Oriente',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9143,'Parumasan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9886,'Soi Dao',NULL,'22180');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4073,'Jezzîne',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (684,'Żoliborz',NULL,'05-094');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7895,'As Saffānīyah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (131,'Igurusi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9445,'Palaiseau','Île-de-France','91124 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6761,'Tulusmulyo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6638,'Longxi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5316,'Francisco I Madero','Zacatecas','98351');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9981,'Cambará',NULL,'86390-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1058,'Padangguci',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4150,'Djambala',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3326,'Linköping','Östergötland','582 31');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2882,'Kedung',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6356,'Cicayur',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9076,'Shapaja',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7876,'Chuguyevka',NULL,'692607');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6864,'Żabbar',NULL,'ZBR');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1447,'Bazha',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2390,'Huddinge','Stockholm','141 21');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4193,'Gaoshibei',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9529,'Apeldoorn','Provincie Gelderland','7329');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (135,'Kuwumkumambal',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4539,'Concepción',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9530,'Umeå','Västerbotten','901 02');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4084,'Youkaichi',NULL,'958-0052');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8031,'Rattanaburi',NULL,'85120');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8358,'Cigembong',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9353,'Saraburi',NULL,'18190');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6213,'Memphis','Tennessee','38197');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9545,'Kieta',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9788,'Wakkanai',NULL,'763-0231');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7301,'Yongtai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6875,'Burtunay',NULL,'368150');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2426,'Mysiadło',NULL,'05-509');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3158,'Maopingchang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (983,'Gutian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1527,'Envigado',NULL,'055428');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3861,'Haikoudajie',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2163,'Sut-Khol’',NULL,'668150');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1884,'Kulykiv',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2443,'Casal do Conde','Santarém','2330-524');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3795,'Pecna',NULL,'64-020');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1493,'União da Vitória',NULL,'84600-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6380,'San Salvador',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1332,'Xianning',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4756,'San Agustin',NULL,'8305');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (44,'Ancona','Marche','60129');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3132,'Boroon',NULL,'9201');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8928,'Gedongmulyo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2103,'Laxou','Lorraine','54529 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5363,'Weishan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1254,'Kołbiel',NULL,'05-340');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2213,'Ciomas',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (822,'Chuarrancho',NULL,'01061');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1583,'Puolanka',NULL,'89201');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5596,'Hushan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2751,'Melaka','Melaka','75518');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5048,'Vrakháti',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5436,'Itaperuçu',NULL,'83560-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2341,'Helsingborg','Skåne','251 08');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9320,'Beyla',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (301,'Jianba',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5957,'Odeleite','Faro','8950-355');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7364,'Yunshan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8205,'Dowsk',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9988,'Tsarychanka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9066,'Ayaviri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4486,'Tinawagan',NULL,'4425');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7363,'Eldoret',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5541,'Vale de Touros','Setúbal','2950-137');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8132,'Taisen-ri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1683,'Jakobstad',NULL,'68660');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6419,'Kołaczyce',NULL,'38-213');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (714,'Pétionville',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8755,'Sigma',NULL,'5816');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7371,'Áno Sýros',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5371,'Lebedyn',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3288,'Shijing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8454,'Rochester','New York','14652');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2682,'Villa Carlos Paz',NULL,'5152');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2769,'Bulbul',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7578,'Baie-D''Urfé','Québec','H9X');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1121,'Pingkai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6662,'Longshan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5409,'Xiaoqi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5557,'Pretoria',NULL,'0204');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7657,'Kotovsk',NULL,'393194');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5528,'Eindhoven','Provincie Noord-Brabant','5629');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2452,'Koryukivka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3969,'Jarinu',NULL,'13240-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4420,'Jājarm',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3226,'Seixo da Beira','Coimbra','3405-425');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (539,'Itaquyry',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6911,'Guangyuan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8191,'Jasugih Selatan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9934,'Lāmerd',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5988,'San Diego','California','92105');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9043,'Abovyan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6685,'Manacapuru',NULL,'69400-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5048,'Vrakháti',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8435,'Mirovka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4719,'El Paso','Texas','79934');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (662,'Santa Luzia','Ilha do Pico','9940-125');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1159,'Heung-hai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8896,'Modakeke',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7709,'Paris 15','Île-de-France','75729 CEDEX 15');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7455,'Utkivka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5826,'Viengxay',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3320,'Paço','Viana do Castelo','4910-060');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1308,'Vyritsa',NULL,'188382');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1493,'União da Vitória',NULL,'84600-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5906,'Wangcungang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8396,'Paris 13','Île-de-France','75638 CEDEX 13');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2090,'Beskolen',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4560,'Ngujuran',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (851,'Tegalsari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2287,'Muhos',NULL,'91501');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3299,'Siliana',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4192,'Skrunda',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4148,'Miyakonojō',NULL,'889-1912');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1393,'Visconde do Rio Branco',NULL,'36520-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9949,'Antigonish','Nova Scotia','B2G');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (354,'Sokol',NULL,'682574');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6589,'Baojia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9829,'Aubervilliers','Île-de-France','93321 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9733,'Deventer','Provincie Overijssel','7409');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5138,'Bzou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7577,'Žacléř',NULL,'542 01');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7985,'Ágios Efstrátios',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1048,'Szydłowo',NULL,'64-930');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8302,'Shuibian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5281,'Almere Haven','Provincie Flevoland','1360');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9549,'Peuara',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8901,'Wuku',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6627,'Campurrejo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3353,'Wuqiao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9646,'Gândara','Viseu','3450-405');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8755,'Sigma',NULL,'5816');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (712,'Herīs',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8051,'Corralillo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3035,'Aylmer','Ontario','N5H');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6709,'Cajamarca',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4455,'Quintong',NULL,'2417');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8962,'Pinggirsari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5926,'Ressano Garcia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9552,'Langford','British Columbia','V9C');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5295,'Nyrkiv',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5416,'Perechyn',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8722,'Sámara',NULL,'50205');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9720,'Al Burayqah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2116,'Węgorzyno',NULL,'73-155');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2040,'Lingda',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2023,'Cincinnati','Ohio','45249');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4609,'Oltinko’l',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5472,'Chãos','Braga','4830-813');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1265,'Degeberga','Skåne','297 32');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7558,'Lyon','Rhône-Alpes','69239 CEDEX 02');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (50,'Kil’mez’',NULL,'613570');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9788,'Wakkanai',NULL,'763-0231');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2272,'Pirogovo',NULL,'427010');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4185,'Shibīn al Kawm',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8435,'Mirovka',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6162,'Forshaga','Värmland','667 91');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8928,'Gedongmulyo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9445,'Palaiseau','Île-de-France','91124 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8423,'Klagen',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (769,'Shar’ya',NULL,'157510');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7403,'Dadiharja',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8047,'Lae',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9873,'Reims','Champagne-Ardenne','51679 CEDEX 2');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1332,'Xianning',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7064,'Al Maḩwīt',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2614,'Santa María Ixhuatán',NULL,'06010');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1633,'Bayambang',NULL,'2423');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9282,'Yacuiba',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7876,'Chuguyevka',NULL,'692607');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9651,'Río Tercero',NULL,'5850');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4041,'Włoszczowa',NULL,'29-100');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4150,'Djambala',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6160,'Bočar',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3303,'Sriwing',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2388,'Richmond','Virginia','23289');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9472,'Tiantai Chengguanzhen',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (823,'Yambio',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6382,'Biqiao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8553,'Salam',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (301,'Jianba',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4386,'Ilo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2758,'Ar Rābiyah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9075,'La Guacamaya',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4272,'Alingsås','Västra Götaland','441 28');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (555,'Markaz Mudhaykirah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (758,'Inglewood','California','90305');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8239,'Tost',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2909,'Kebonan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4655,'Ponyri Vtoryye',NULL,'452056');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4239,'Ust-Maya',NULL,'678620');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4649,'Aragua de Barcelona',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2201,'Nangerang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7452,'Jiangzhang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9282,'Yacuiba',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6204,'Gueset',NULL,'2436');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4030,'Karangkeng',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5988,'San Diego','California','92105');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (714,'Pétionville',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5437,'Nueva Esperanza','Veracruz Llave','94242');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8431,'Atawutung',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (92,'Guéret','Limousin','23009 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9375,'Ntungamo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8228,'Yinjiaxi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (822,'Chuarrancho',NULL,'01061');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7129,'Jahāniān Shāh',NULL,'40231');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1971,'Tongren',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8448,'Konary',NULL,'63-910');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (784,'Osypenko',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (555,'Markaz Mudhaykirah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1047,'Arrentela','Setúbal','2840-146');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6685,'Manacapuru',NULL,'69400-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (756,'Donggang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (545,'Qijiawan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7378,'Sambirobyong',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (495,'Algeciras',NULL,'413048');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3353,'Wuqiao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7572,'Kai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4120,'Budagovo',NULL,'665236');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9529,'Apeldoorn','Provincie Gelderland','7329');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9378,'Janagdong',NULL,'1808');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4151,'Sambuluan',NULL,'1144');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9855,'Panalingaan',NULL,'9610');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9729,'Tavira','Faro','8800-303');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1159,'Heung-hai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (383,'Ganxi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4790,'Sebeta',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4486,'Tinawagan',NULL,'4425');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6451,'Maghār',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4564,'Sulengwaseng',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3108,'Ehen Hudag',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3967,'Orsay','Île-de-France','91851 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5439,'Sukamulia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1657,'Nankou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8668,'Saint Louis','Missouri','63180');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3357,'Togur',NULL,'636450');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7335,'La Esperanza',NULL,'546058');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8461,'Poissy','Île-de-France','78304 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7310,'Nong Yai',NULL,'20190');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (784,'Osypenko',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3522,'Mosrentgen',NULL,'391237');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5439,'Sukamulia',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3274,'Austin','Texas','78759');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7672,'Cikuya',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7405,'Barbacena',NULL,'36200-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4880,'Orly aérogare','Île-de-France','94542 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3074,'Damanhūr',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9675,'São Marcos',NULL,'95190-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2409,'Xiongshan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1361,'Kizhinga',NULL,'671450');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9829,'Xianglong',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1254,'Wręczyca Wielka',NULL,'42-284');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9628,'Ponte','Viseu','3680-191');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4454,'Villach','Kaernten','9580');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3721,'Jetis',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7403,'Dadiharja',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5886,'Xuedian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (216,'Youxikou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5652,'Orange','Provence-Alpes-Côte d''Azur','84104 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2812,'Tangerang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9432,'Xarrë',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (852,'Komorniki',NULL,'62-056');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (634,'Panggungasri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2291,'Virginia',NULL,'D18');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6311,'Ţawr al Bāḩah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6574,'Shaykh al Ḩadīd',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9994,'Danirai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5289,'Matou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2103,'Laxou','Lorraine','54529 CEDEX');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8205,'Dowsk',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (742,'Kista','Stockholm','164 73');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5599,'Karlshamn','Blekinge','374 81');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4148,'Miyakonojō',NULL,'889-1912');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8836,'Laval','Québec','H7S');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (399,'Shicong',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9715,'Sawin',NULL,'22-107');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3427,'Okazaki',NULL,'800-0331');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2192,'Lamarosa','Coimbra','3025-389');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6455,'Areeiro','Portalegre','7300-440');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2653,'Kebon',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1048,'Szydłowo',NULL,'64-930');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7077,'Novotroitsk',NULL,'613151');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3143,'Sihai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9264,'Rio Claro',NULL,'13500-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (841,'Gotputuk',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3110,'Qingkou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4386,'Ilo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2545,'Düsseldorf','Nordrhein-Westfalen','40591');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3799,'Dalupirip',NULL,'2922');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3887,'Granard',NULL,'D09');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1463,'Nikolinci',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9675,'São Marcos',NULL,'95190-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7443,'Sabana Grande de Boyá',NULL,'10136');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6229,'Kanturk',NULL,'K36');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1916,'Dhamār',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8970,'Shanghuang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2449,'Luotaping',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2163,'Sut-Khol’',NULL,'668150');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6612,'Novki',NULL,'601340');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9528,'Johanneshov','Stockholm','121 48');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4157,'Dalianhe',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5886,'Xuedian',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9261,'Botou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3260,'Karawatu',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3544,'Tōno',NULL,'326-0036');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1564,'Novokhovrino',NULL,'141707');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3574,'Roma','Lazio','00196');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8607,'Valencia',NULL,'6306');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1361,'Kizhinga',NULL,'671450');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4281,'Zhongpai',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5363,'Weishan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9075,'La Guacamaya',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (409,'Susanino',NULL,'157090');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7997,'Agualote',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9601,'Xilópolis',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2023,'Cincinnati','Ohio','45249');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6359,'Muaraenim',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9715,'Sawin',NULL,'22-107');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7452,'Jiangzhang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9012,'Gaza',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6496,'San Rafael',NULL,'5039');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1880,'Terenozek',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4030,'Karangkeng',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4148,'Miyakonojō',NULL,'889-1912');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7577,'Žacléř',NULL,'542 01');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8962,'Pinggirsari',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3597,'Atakpamé',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4201,'Sviblovo',NULL,'607224');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (300,'Santa Cruz do Rio Pardo',NULL,'18900-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3943,'Ballybofey',NULL,'V23');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5144,'Farah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2426,'Mysiadło',NULL,'05-509');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8132,'Taisen-ri',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5371,'Lebedyn',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2104,'Gavião','Portalegre','6040-104');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5914,'Colcabamba',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1447,'Bazha',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1549,'Prata',NULL,'58550-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1008,'San Rafael Oriente',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3545,'Saqqez',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7364,'Yunshan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9839,'Ronov nad Doubravou',NULL,'538 42');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4609,'Oltinko’l',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7268,'Xiamao',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9057,'Kebonkaret',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8901,'Wuku',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5395,'Dū Qal‘ah',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (44,'Ancona','Marche','60129');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4073,'Jezzîne',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6890,'Uvarovo',NULL,'393479');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9813,'Sibaté',NULL,'111971');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1493,'União da Vitória',NULL,'84600-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9264,'Rio Claro',NULL,'13500-000');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6047,'Karanglo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6511,'Sundsvall','Västernorrland','851 06');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4251,'Karlskoga','Örebro','691 34');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3539,'Jobabo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5623,'Stenungsund','Västra Götaland','444 32');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1392,'Vegreville','Alberta','T9C');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6419,'Kołaczyce',NULL,'38-213');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5152,'Ewirgol',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5471,'Muḩammad Āghah Wuluswālī',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (135,'Kuwumkumambal',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6600,'General Pinedo',NULL,'3732');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9047,'Los Angeles','California','90040');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3158,'Maopingchang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5518,'Sacramento','California','95818');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1463,'Nikolinci',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4996,'Zarumilla',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (3427,'Okazaki',NULL,'800-0331');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (9265,'Perpignan','Languedoc-Roussillon','66019 CEDEX 9');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (539,'Itaquyry',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5599,'Karlshamn','Blekinge','374 81');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4562,'Xiaolou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8228,'Yinjiaxi',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8668,'Saint Louis','Missouri','63180');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (5175,'Nyaunglebin',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (2697,'Kiuola',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1916,'Dhamār',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (8214,'Qiaotou',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4580,'Karasuk',NULL,'632868');
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (6911,'Guangyuan',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1955,'Krajan Tanjungrejo',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (7468,'Gaoliang',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (4865,'Jiahe',NULL,NULL);
INSERT INTO AuthorAddress(authorid,city,state,zip) VALUES (1555,'Yambol',NULL,'8600');
