Use BookBank;

INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6232,'Zhicheng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (159,'Burujul',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1177,'Fernando Gutierrez Barrios','Veracruz Llave','93420');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7071,'Niška Banja',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4502,'Evansville','Indiana','47732');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9818,'Sanjiangkou',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4051,'Anserma',NULL,'177089');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4218,'Salta',NULL,'4400');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (872,'Reshui',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3330,'As Sayyānī',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8101,'Dijon','Bourgogne','21040 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6134,'Heshi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6299,'Seattle','Washington','98195');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2217,'San Rafael',NULL,'5039');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6661,'Kysyl-Syr',NULL,'678214');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2054,'Kalibuntu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5174,'Polazna',NULL,'618703');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6004,'Belfort','Franche-Comté','90020 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6313,'Manzanillo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3932,'Picoto','Braga','4830-073');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4329,'Tabwakea Village',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3154,'Zhaocun',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6190,'Luanshya',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7707,'Loutrós',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4423,'Puncaksari',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1922,'Otan Aiyegbaju',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6485,'Potlot',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2065,'Bella Vista',NULL,'9400');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2636,'Bairan',NULL,'4511');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7120,'Mandalasari',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1183,'Kotlovka',NULL,'142817');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4918,'Sanhui',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9813,'Xinzha',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1784,'Houk',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6112,'Fuzhiping',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5614,'Longtan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2559,'Ningtang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5641,'Busungbiu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8721,'Banyubang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5710,'L’vovskiy',NULL,'142390');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7528,'Bol’shoye Selo',NULL,'391147');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (181,'Phatthalung',NULL,'73130');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6091,'La Unión',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1264,'Sotomayor',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4672,'Apače',NULL,'9253');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2971,'Puubheto',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (941,'Annecy-le-Vieux','Rhône-Alpes','74944 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8049,'Changtan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5962,'Heiheba',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6655,'‘Abbāsābād',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2356,'Tiyingtali Kelod',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3486,'Aimadamodo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3530,'Houston','Texas','77090');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9065,'Ngori',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8478,'Ladário',NULL,'79370-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2441,'Strzelce',NULL,'99-307');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1415,'Pinagsibaan',NULL,'0801');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7718,'Marieville','Québec','J3M');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6862,'Moutsamoudou',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8517,'Lembur Tengah',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4438,'Shiraz',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7978,'Mandepa Barat',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8409,'San Francisco',NULL,'8501');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3682,'Fatumnasi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8078,'Thap Khlo',NULL,'71000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7897,'Gaza',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4629,'Ipoh','Perak','30620');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5233,'Dafundo','Lisboa','1495-701');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1951,'Yakovlevo',NULL,'215723');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2528,'Kupahandap',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9637,'Pakxong',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7364,'Buenavista','Mexico','54414');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2494,'Aubergenville','Île-de-France','78415 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8462,'Qiawan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8765,'Phrae',NULL,'54130');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2218,'Shenkou',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2334,'Mostek',NULL,'565 01');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7024,'Nové Sedlo',NULL,'438 01');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2692,'Darvi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9559,'Talok',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4194,'Yushan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6386,'Cordon',NULL,'3312');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7711,'Suresnes','Île-de-France','92154 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6518,'Moyo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6810,'Torres Novas','Santarém','2350-413');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (331,'Châteaurenard','Provence-Alpes-Côte d''Azur','13834 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2555,'Illela',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7224,'Klirou',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6013,'Longsheng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7426,'Laprida',NULL,'4205');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7527,'Notre Dame',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2287,'Jitian',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5526,'Santiaoshi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1585,'Poste de Flacq',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2741,'Bosanski Novi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1734,'Nambak Tengah',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7344,'Yangcheng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4694,'Sande Vila Nova','Braga','4805-556');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1171,'Menggala',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9574,'Bayt Liqyā',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4781,'Inda Silasē',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (271,'Đắk Mil',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9786,'North Shore',NULL,'0748');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4836,'Makiyivka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2465,'Tegallega',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8986,'Louisville','Kentucky','40287');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3845,'Dailekh',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3175,'Taphan Hin',NULL,'66110');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5213,'Las Lomas',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (88,'Bantardawa',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1638,'Tieshan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7360,'Andongsari',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3542,'Sandgerði',NULL,'245');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4852,'Prochowice',NULL,'59-230');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9319,'Da’an',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (732,'Golbey','Lorraine','88194 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4479,'Santa Rita Village',NULL,'96910');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (138,'Angers','Pays de la Loire','49033 CEDEX 01');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9420,'Rosmalen','Provincie Noord-Brabant','5249');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4484,'Bani',NULL,'2407');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2715,'Oljoq',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8148,'Chengzhong',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1128,'Hŭkkyo-ri',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2391,'Seren',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (758,'Štítná nad Vláří',NULL,'763 33');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6991,'Liutangting',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8614,'Sâmraông',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7335,'Koton Karifi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5443,'Lubao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7928,'As Sūsah',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3695,'Berëza',NULL,'446392');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8715,'Charagua',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7367,'San Mariano',NULL,'3332');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2660,'Porangaba',NULL,'18260-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5382,'Maroúsi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1224,'Yeshan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1688,'Huallanca',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6244,'Tierimu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9770,'Khlong Khuean',NULL,'34280');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9492,'Dongxiang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5300,'Марино',NULL,'1047');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4175,'Malin',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7827,'Maxiao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8591,'Sembalunbumbung',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7358,'Salamanca',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6210,'Söderhamn','Gävleborg','826 31');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8610,'Changxingbao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9097,'Nunbaundelha',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3147,'Brańsk',NULL,'17-120');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6008,'Las Carreras',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6011,'Urazovo',NULL,'309975');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5161,'Megati Kelod',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (80,'Huangqiao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1322,'Marietta','Georgia','30061');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8344,'Rebe',NULL,'9214');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3386,'Hicksville','New York','11854');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1040,'Washington','District of Columbia','20535');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2647,'Bayt al ‘Awābī',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9860,'Turbaco',NULL,'131008');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2640,'Svalyava',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6446,'Ростуша',NULL,'1257');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9694,'Ralevka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5985,'Portland','Oregon','97271');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (106,'Castanheira do Campo','Coimbra','3025-511');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1641,'Timpas',NULL,'5805');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3097,'Caringin',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1444,'Champigny-sur-Marne','Île-de-France','94504 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (207,'Banjar Banyualit',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2605,'Namling',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8759,'Xiadian',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9322,'Pulangbato',NULL,'6711');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7286,'Priekulė',NULL,'96047');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4010,'Oli',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (518,'Chuoyuan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6299,'An Naşşārīyah',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9494,'Lovran',NULL,'51415');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9909,'Zbytków',NULL,'90-360');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (784,'Chalcos',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6782,'Valenciennes','Nord-Pas-de-Calais','59304 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3801,'Renhe',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9526,'Jabungsisir',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9149,'Lyubimets',NULL,'6522');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8289,'Pasirmadang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3552,'Veisiejai',NULL,'67043');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8086,'Kalimeneng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5134,'Miguel Hidalgo','Guerrero','39120');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1609,'Zhutian',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8734,'Bayan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5026,'Pirogovo',NULL,'427010');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (135,'Cabannungan Second',NULL,'3300');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5728,'Jiquilillo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6791,'Alvaiázere','Leiria','3250-104');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3108,'Zhoinda',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1800,'Dengnan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5143,'Łapczyca',NULL,'32-744');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8573,'La Gomera',NULL,'05007');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9572,'Patambuco',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6928,'Proletar',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7920,'Valdosta','Georgia','31605');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1169,'Satu Nou','Vaslui','737513');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7350,'Karungdong',NULL,'7214');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4550,'Thị Trấn Phước Bửu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9682,'Sinŭiju',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2670,'Loacan',NULL,'2612');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6320,'La Bélgica',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5455,'Independencia','Chiapas','30815');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2318,'Xinzhuang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6200,'Chating',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7274,'Miguel Hidalgo','Veracruz Llave','91140');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8053,'Shah Alam','Selangor','40582');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1810,'Tabivere',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3698,'Pubal',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6220,'Podstrana',NULL,'53213');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3726,'Longmiao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1716,'Nglego',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3440,'Marolambo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4661,'Lincuo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4973,'Ulricehamn','Västra Götaland','523 32');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5742,'Suocheng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3282,'Västerås','Västmanland','724 63');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6119,'Now Zād',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5373,'Xinpo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4532,'Fëdorovskoye',NULL,'196625');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2435,'Anse Royale',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2773,'Langkaplancar',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5813,'Amarillo','Texas','79165');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2926,'Zeqin',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1897,'Yingcheng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6946,'Itumbiara',NULL,'75500-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6551,'Tha Ruea',NULL,'13130');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9407,'Karangbalong',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (865,'Diyarb Najm',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (95,'Shatura',NULL,'140704');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5866,'Lukolela',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3992,'Rejoso',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1634,'Jiaze',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (391,'Ar Rahad',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4736,'Baicheng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3299,'Aldeia de Juzo','Lisboa','2750-015');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1436,'Baton Rouge','Louisiana','70820');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3792,'Zhangdian',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9713,'Logung',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3492,'Karditsomagoúla',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8977,'Nentón',NULL,'13005');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2899,'Brive-la-Gaillarde','Limousin','19318 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8876,'Chongqing',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5269,'Shatoujiao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5851,'Härnösand','Västernorrland','871 33');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6226,'Banisilan',NULL,'9416');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5345,'Panadura',NULL,'12500');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1934,'Riti',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4965,'Morón',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1274,'Ancenis','Pays de la Loire','44159 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5962,'Berlín',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5492,'Le Grand-Quevilly','Haute-Normandie','76124 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4178,'Höganäs','Skåne','263 36');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3200,'Tyresö','Stockholm','135 50');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2746,'Banjar Anyar',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4845,'Villiers',NULL,'9840');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3026,'Jesús Menéndez',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3418,'Gyamco',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3830,'Colón',NULL,'3280');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9714,'Prizren',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1746,'Cầu Gồ',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1639,'Wujiao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9313,'Kuusjoki',NULL,'25330');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2480,'Heze',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (664,'Yanshang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2115,'Tangxi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1169,'Dacun',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3238,'Dumlan',NULL,'8119');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8253,'Song’ao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4436,'Boca de Parita',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8579,'Tangjin',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2351,'Karamat',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6985,'Maying',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7544,'Villamaría',NULL,'176008');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4862,'Kamensk-Ural’skiy',NULL,'623462');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6559,'Fuchang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5703,'Tolú',NULL,'706018');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5191,'Sardasht',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9680,'Mooirivier',NULL,'3300');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6674,'Banjar Tengah',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8279,'Tarascon','Provence-Alpes-Côte d''Azur','13155 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7778,'Registro',NULL,'11900-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (770,'Zhicheng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4157,'Cisoka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8786,'Gevgelija',NULL,'1480');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2784,'Hongxi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2392,'Botshabelo',NULL,'9789');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8521,'Teodoro Sampaio',NULL,'19280-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3980,'Mairinque',NULL,'18120-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4411,'Nevers','Bourgogne','58017 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5886,'Savannah','Georgia','31422');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8042,'Kotablolong',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8176,'Borås','Västra Götaland','504 67');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8965,'Girón',NULL,'687587');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2950,'كاف الجاع',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5845,'Comé',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9496,'Tongkiling',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2191,'Kawangu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2364,'Kudang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6681,'Marília',NULL,'17500-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7860,'Malianchuan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1861,'Los Juríes',NULL,'3763');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (920,'La Unión',NULL,'704057');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3015,'Yushan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6859,'Johor Bahru','Johor','80600');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5542,'Schellenberg',NULL,'9488');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6599,'Krujë',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2613,'Palagao Norte',NULL,'0918');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1790,'Sơn Hà',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9979,'Cholet','Pays de la Loire','49309 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (145,'Kampungtengah',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5620,'Choropampa',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5245,'Carpina',NULL,'55810-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (597,'Santa Elena de Uairén',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1766,'Huochang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6848,'Ukrainka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5555,'Marolambo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (48,'Konibodom',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6565,'Zhongxing',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3325,'Courtaboeuf','Île-de-France','91959 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1232,'Lapinjärvi',NULL,'07800');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3626,'Khotynets',NULL,'303930');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (301,'Best','Provincie Noord-Brabant','5684');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (664,'Likasi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2437,'Naikolan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9811,'Komsomol’sk',NULL,'155150');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5978,'El Mirador','Veracruz Llave','93429');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (269,'Aubagne','Provence-Alpes-Côte d''Azur','13681 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6876,'Kolsko',NULL,'67-415');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8915,'Dusit',NULL,'10300');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8076,'Sarpang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6059,'Chengnan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9429,'Chongwen',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1416,'Kuala Lumpur','Kuala Lumpur','50943');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4766,'Pentéli',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5601,'Sidomakmur',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5601,'Heishui',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2269,'Sulahan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (511,'Bau',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8950,'Itaperuna',NULL,'28300-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3393,'Zinder',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4085,'Sarulla',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (76,'Hongdun',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5762,'Puerto Princesa',NULL,'5300');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (55,'Ljupina',NULL,'35400');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4835,'Yangying',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5100,'Orahovac',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5885,'Yermish’',NULL,'391660');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1265,'Pocokan Satu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1672,'Kanash',NULL,'429337');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5711,'Kampong Chhnang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8875,'Bāzārak',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2567,'Carquefou','Pays de la Loire','44474 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9925,'Hutang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2014,'Marquard',NULL,'9610');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9141,'Kampunglistrik',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1531,'Biryulëvo Zapadnoye',NULL,'396689');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1826,'Severo-Zadonsk',NULL,'301792');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5055,'Hankasalmi',NULL,'41521');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6558,'Tocopilla',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8438,'Zhalinghu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7051,'Girón',NULL,'687587');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4828,'Abreu e Lima',NULL,'53500-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7578,'Berezniki',NULL,'618409');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4863,'Nong Phai',NULL,'67140');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4387,'Qianpai',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5695,'Río Cauto',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2485,'Sargodha',NULL,'67391');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6807,'Tchaourou',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7649,'Hovtashen',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2749,'Los Angeles','California','90030');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1378,'Ferraz de Vasconcelos',NULL,'08500-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2587,'El Bolsón',NULL,'8430');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9959,'Nanterre','Île-de-France','92885 CEDEX 9');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9947,'Gizo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1453,'Skotoússa',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5044,'Jinotepe',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4943,'Wangcun',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (56,'Honghuatao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8473,'Księżpol',NULL,'23-415');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3302,'Maceda','Aveiro','3885-705');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6166,'Tim',NULL,'399710');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1620,'Shijing',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6413,'Lukou',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4410,'Ḏânan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5211,'Tawau','Sabah','91020');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2907,'Wattala',NULL,'11104');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6961,'Šid',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9746,'Tanjung Timur',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9691,'Kariya',NULL,'969-1619');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9750,'Amphawa',NULL,'75110');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7475,'Binjai',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6348,'Limbe',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2406,'Brzeg Dolny',NULL,'56-122');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4490,'Cikuray',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9149,'Pinheiros',NULL,'29980-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3458,'Suocheng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6666,'Rožďalovice',NULL,'289 34');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (477,'Sugiharjo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2172,'Buenavista',NULL,'8601');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1639,'Jingmao',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4921,'Sanli',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8829,'Chvalšiny',NULL,'382 08');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1025,'San Francisco de Coray',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1658,'Lons-le-Saunier','Franche-Comté','39039 CEDEX 9');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5883,'Shaliangzi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6894,'Obolo-Eke (1)',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7801,'Kulykiv',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4571,'Choros',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7462,'Sigeng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4095,'Ordem','Leiria','2430-159');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7419,'Minneapolis','Minnesota','55448');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1838,'Horki',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8399,'Turki',NULL,'412091');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1296,'Beberon',NULL,'4312');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3026,'Xuetian',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6013,'Taipa',NULL,'0420');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9709,'Potlot',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3102,'Cantuk Kidul',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2071,'Ewarton',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6838,'Hà Tiên',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9572,'Fuchun',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6412,'Fengchuan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6259,'San Pascual',NULL,'5420');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9433,'Shin’ichi',NULL,'729-3111');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9215,'Moycullen',NULL,'A41');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7847,'Zhatay',NULL,'182514');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6203,'Hatton','England','CV35');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5772,'San Jose','California','95108');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9395,'Qiankeng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8916,'Ilesa',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5275,'Blagnac','Midi-Pyrénées','31709 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3512,'Banjar Petak',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4134,'Náchod',NULL,'547 01');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4175,'Yuchi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (692,'Javānrūd',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5512,'Patos',NULL,'58700-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2598,'Sacsamarca',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2296,'Hutang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6704,'Baz',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6237,'Meilisi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5159,'Karawatu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2238,'San Lorenzo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7234,'Valinhos',NULL,'13270-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3433,'Qianfoling',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4532,'Paungde',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3206,'Malummaduri',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3784,'Mons','Wallonie','7032');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6644,'Liangshan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4688,'Gložan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (408,'Słubice',NULL,'69-101');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5016,'Mazār-e Sharīf',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4688,'Bulawin',NULL,'7416');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4940,'Diang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2736,'Stepanivka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1486,'Barkā’',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6085,'Cotuí',NULL,'10210');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5205,'Mwinilunga',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3086,'Calatrava',NULL,'6126');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7830,'Vilémov',NULL,'783 22');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5797,'Piraí do Sul',NULL,'84240-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4163,'Zduńska Wola',NULL,'98-231');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7348,'Guaratuba',NULL,'83280-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8437,'Boca Raton','Florida','33499');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9299,'Sanxing',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2636,'Maloarkhangel’sk',NULL,'303370');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9822,'Mancagahar',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (926,'Cinangka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7884,'Gémeos','Braga','4810-571');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4357,'Porto Alegre',NULL,'90000-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3843,'Kokkári',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4247,'Samālūţ',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7303,'Mentougou',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4257,'Lagoaça','Bragança','5180-205');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2417,'Zarszyn',NULL,'38-524');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3801,'Banjarjo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4353,'Strawberry Hills','New South Wales','1424');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4809,'Kostyantynivka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7867,'Bělá pod Bezdězem',NULL,'294 21');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6892,'Puyang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (107,'Zhenziliang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2193,'Romorantin-Lanthenay','Centre','41204 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9177,'Baochang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5006,'Bungbulang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9987,'Huidong',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2165,'Mafa',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6880,'Fengle',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2915,'Toamasina',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3018,'Nice','Provence-Alpes-Côte d''Azur','06182 CEDEX 2');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6676,'Anaco',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1154,'Paradela','Bragança','5210-264');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8628,'Susunan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9131,'Simrishamn','Skåne','272 24');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (106,'Kryevidh',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3367,'Berlin','Berlin','14109');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2146,'Koloniya Zastav’ye',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7473,'Vallentuna','Stockholm','186 53');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8855,'Pangalangan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1711,'Mucumpiz',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7482,'Maragogipe',NULL,'44420-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (697,'Myingyan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1685,'San Felipe',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6981,'Głuchów',NULL,'96-130');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9176,'Faaone',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8876,'Yangping',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9517,'Birobidzhan',NULL,'152430');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6905,'Liangshan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8264,'Beška',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2833,'Niaohe',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9596,'Sleman',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6803,'Molepolole',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4235,'Gongpo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4418,'Skellefteå','Västerbotten','931 77');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2140,'Hejia',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3885,'Xiadian',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (207,'Qinghaihu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9890,'Logung',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5925,'Sutton','England','RH5');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2513,'Neochóri',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9346,'Tyler','Texas','75799');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8959,'Babahoyo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2993,'Riđica',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (480,'Babirik',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6773,'Nhà Bàng',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7676,'Laimuda',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1271,'Lukou',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1206,'Tsotsin-Yurt',NULL,'368033');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1207,'Křížová',NULL,'794 01');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9161,'Takeshiken',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9188,'Jagüey Grande',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1284,'Topolná',NULL,'687 11');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4054,'Helsingborg','Skåne','250 06');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7755,'Tyukalinsk',NULL,'646334');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4276,'Huangtian',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5600,'Yatunpu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4159,'Ziyang Chengguanzhen',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2180,'Ngampon',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7013,'Dadong',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2180,'Shawnee Mission','Kansas','66225');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2468,'Portel',NULL,'68480-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6076,'Sandakan','Sabah','90716');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2974,'Munse',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9550,'Yonghe',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1212,'Si Narong',NULL,'34000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8450,'Liutang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7754,'Sollefteå','Västernorrland','881 86');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6243,'Santiago de los Caballeros',NULL,'11403');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7690,'Shambu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6660,'Sofiyivka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3277,'Xaçmaz',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2510,'Aloja',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7463,'Brengkok',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2892,'Leshukonskoye',NULL,'164670');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5273,'Parakanbeusi',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5016,'Maceió',NULL,'57000-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (117,'Pasongsongan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5089,'La Quiaca',NULL,'3461');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1922,'Milano','Lombardia','20158');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4997,'Los Angeles','California','90045');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (55,'Burtunay',NULL,'368150');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8435,'Quanling',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8092,'María la Baja',NULL,'131077');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4228,'Usatove',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3359,'Cisewu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8681,'Zwolle','Provincie Overijssel','8019');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (290,'Donja Dubica',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6833,'Guanagazapa',NULL,'22017');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3581,'Bojongloa',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9129,'San Jacinto',NULL,'5417');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1863,'Korolevo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5404,'Bariri',NULL,'17250-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3690,'Zoumaping',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9590,'Salas',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3424,'Lahishyn',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3160,'Bourg-en-Bresse','Rhône-Alpes','01069 CEDEX 9');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5225,'Las Flores','Coahuila De Zaragoza','25290');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (41,'Södertälje','Stockholm','152 31');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2922,'Ḩātim',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6189,'Luofang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (921,'Granada',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2915,'Yetang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8248,'Baume-les-Dames','Franche-Comté','25117 CEDEX');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4772,'Ouani',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9085,'Valencia',NULL,'6306');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5204,'Bŭka',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6673,'Cruzeiro','Viana do Castelo','4960-110');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2508,'Xibu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2863,'Duwe',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2349,'Itatiba',NULL,'13250-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5677,'Bradenton','Florida','34282');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5924,'Simabur',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9402,'Pasadena','California','91131');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8220,'Jabranti',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8125,'Thị Trấn Thanh Lưu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3839,'Gowarczów',NULL,'26-225');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5916,'Svetogorsk',NULL,'188992');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1675,'Tikhoretsk',NULL,'422120');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (743,'Sumberpinang Satu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (531,'Quán Hàu',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3236,'Tobias Barreto',NULL,'49300-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (516,'Piltown',NULL,'T34');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3464,'Bhola',NULL,'3633');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2644,'Ukmerge',NULL,'20012');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7935,'Lilio',NULL,'4004');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (797,'Pontal',NULL,'14180-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3082,'Taibai',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (651,'Ingeniero Guillermo N. Juárez',NULL,'3636');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2754,'Rakek',NULL,'1381');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4567,'Pu’er',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5657,'Ḩarastā',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8083,'Taremskoye',NULL,'606135');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4752,'Changle',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9854,'Sidomulyo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5731,'Salamá',NULL,'15001');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5796,'Lesnoy',NULL,'431107');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4067,'Bugis',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5203,'Čejkovice',NULL,'671 65');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8770,'Bobrovka',NULL,'457134');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7693,'Seixal','Setúbal','2840-466');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5875,'Trudobelikovskiy',NULL,'353810');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7753,'Raduzhnyy',NULL,'601380');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2794,'Emiliano Zapata','Guanajuato','38703');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4373,'Youxi Chengguanzhen',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6872,'Qiashui',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6871,'Värnamo','Jönköping','331 29');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3352,'Paris 11','Île-de-France','75547 CEDEX 11');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4983,'Dikhil',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2904,'Sembungan Kidul',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (4488,'El Mirador','Veracruz Llave','93429');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3570,'Ciro Redondo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5797,'Bauru',NULL,'17000-000');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6432,'Putukrejo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (9318,'Abdurahmoni Jomí',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (5262,'Muraharjo',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1670,'Skatepark','Ontario','K7R');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (3858,'Saint Croix',NULL,'00851');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (6861,'Citambal',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (278,'Caraballeda',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (8632,'Staryy Cherek',NULL,'361327');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1014,'Chaoyang',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (668,'Juhut',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (2408,'Sovetakan',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (1029,'Handegate',NULL,NULL);
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (7114,'Wolmaransstad',NULL,'2630');
INSERT INTO CuratorAddress(curatorid,city,state,zip) VALUES (225,'Renko',NULL,'14300');