USE BookBank;

INSERT INTO UserAddress(userid,city,state,zip) VALUES (2224,'Cortez',NULL,'8313');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3565,'Portorož',NULL,'6333');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8773,'Kalix','Norrbotten','952 61');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5858,'Jetak Kulon',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5035,'Jorochito',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1081,'Ko Si Chang',NULL,'55120');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6406,'Neofbaun',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (426,'Aix-en-Provence','Provence-Alpes-Côte d''Azur','13540');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9409,'Lingqian',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6120,'Fayzabad',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (839,'Miaoyu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3958,'Carriedo',NULL,'4710');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5102,'Ovidiopol’',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7411,'Bamban',NULL,'2317');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (456,'Langenburg','Saskatchewan','V7P');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4295,'Butel',NULL,'1040');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9253,'Kālābāgh',NULL,'42360');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4844,'Mevo horon',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2161,'Keelung',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2899,'Fayaoué',NULL,'98814');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2730,'Thị Trấn Yên Châu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6416,'Annan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2164,'Junik',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5159,'Staryy Oskol',NULL,'309509');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3536,'Ewirgol',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4869,'Nikol’sk',NULL,'630025');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3850,'Uticyacu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5940,'Thívai',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2002,'Damanhūr',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9648,'Santa Anita','Guanajuato','38900');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8122,'Qinglin',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4543,'Lesogorsk',NULL,'665501');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3903,'Guernica',NULL,'1862');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7082,'Årsta','Stockholm','120 38');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6507,'Evansville','Indiana','47725');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3004,'Ruen',NULL,'8542');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2148,'Vřesina',NULL,'747 20');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2026,'Ríohacha',NULL,'440017');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7895,'Kristianstad','Skåne','291 41');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7102,'Kvasiny',NULL,'517 02');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8566,'Gornje Živinice',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5796,'Binabaan',NULL,'5034');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (799,'Pancol',NULL,'3200');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5556,'Čajetina',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (270,'Shangjing',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3472,'Hongtang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (414,'Gilin',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9235,'Sinŭiju',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6969,'Hà Tĩnh',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9733,'Pyatigorsk',NULL,'357560');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5778,'Sanshengyuan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4072,'Tajerouine',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4900,'Yuta',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1515,'Koch''ang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8621,'Panguruan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3379,'Laoxingchang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3635,'Linan',NULL,'1105');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7894,'Karlskoga','Örebro','691 41');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9157,'Yanmenkou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5219,'Cirangrang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3528,'Kuala Lumpur','Kuala Lumpur','59800');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5899,'Lushuihe',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7519,'Kitwe',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4394,'Monroe','Louisiana','71213');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5724,'Asaita',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9023,'Las Varas',NULL,'5941');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6030,'Banqiao',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7660,'Miyakonojō',NULL,'889-1912');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (253,'Usu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4013,'Itapipoca',NULL,'62500-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9928,'Tindog',NULL,'6012');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6681,'Liufang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5817,'Srubec',NULL,'370 06');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7720,'Mang’it Shahri',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2822,'Rukem',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2607,'Sietesz',NULL,'37-206');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4604,'Zhonghekou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6663,'Fuzhou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7011,'Salinggara',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2595,'Muhos',NULL,'91501');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1367,'Maurisu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9849,'Suruhan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (259,'Alejo Ledesma',NULL,'2662');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3473,'Wichita','Kansas','67236');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1865,'Palhais','Porto','4620-023');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8599,'Pingshan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5867,'Shihuang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1334,'Antsohimbondrona',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2265,'Bealanana',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6503,'Orekhovo-Zuyevo',NULL,'142609');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6274,'Tubo',NULL,'2814');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4877,'Hřebeč',NULL,'571 01');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2992,'Shreveport','Louisiana','71161');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7798,'Cibunar',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3063,'Liwonde',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (166,'Benger',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (172,'Kameoka',NULL,'992-0321');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5066,'Hefei',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9623,'Sarajevo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4426,'Paraparaumu',NULL,'5254');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2480,'Sułów',NULL,'56-306');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (406,'Rakai',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4454,'Budy',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5251,'Donabate',NULL,'K67');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8901,'Athi River',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9155,'Mabini',NULL,'6313');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4404,'Dalheim',NULL,'L-5687');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (593,'Wuxiang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (108,'Cibitung',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2028,'Dongfu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5488,'Agrínio',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5165,'Norfolk','Virginia','23509');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9219,'Ketapang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8268,'Arauca',NULL,'810009');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6575,'Fukuroi',NULL,'437-0026');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2217,'Youxikou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (703,'Belung Satu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3521,'Sumberkemuning',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3163,'Basel','Kanton Basel-Stadt','4085');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9431,'Uzunovo',NULL,'142960');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7042,'Kapshagay',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6911,'Vallegrande',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3686,'Miribanteng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6346,'Stylída',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6873,'Alajuelita',NULL,'11001');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9961,'Shixiang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9340,'Stod',NULL,'333 01');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3317,'Радолишта',NULL,'6339');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8851,'Tarbes','Midi-Pyrénées','65022 CEDEX 9');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5476,'Kota Bharu','Kelantan','15630');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9522,'Ishëm',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3302,'Guadalupe Victoria','Veracruz Llave','93856');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4133,'Sumurber',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1548,'Tyumen',NULL,'625999');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3154,'Adh Dhayd',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3751,'Victoria','British Columbia','V9A');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7725,'Qitan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9802,'Panikihan',NULL,'4307');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3663,'Jiujiang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7221,'North Shore',NULL,'0748');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2235,'Xihanling',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1943,'Krasne',NULL,'36-007');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8253,'Sumbawa Besar',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2629,'Maying',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (196,'Tlogocilik',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3125,'Žabčice',NULL,'664 63');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8145,'Matmata',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2,'Sevlievo',NULL,'5450');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2394,'Cimenga',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5974,'Kälviä',NULL,'68300');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2392,'Nandu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3641,'Sepekov',NULL,'398 51');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3668,'Bissau',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1796,'Formiga',NULL,'35570-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4206,'Falāvarjān',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7680,'Ishimbay',NULL,'453209');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5086,'Yangzhuang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6390,'Pangnirtung','Nunavut','M5T');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3591,'Pedro Santana',NULL,'11705');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6604,'Haninge','Stockholm','136 68');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4537,'Phonphisai',NULL,'43120');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9959,'Yubileyny',NULL,'249087');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3534,'Changjiang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6741,'Cañada de Gómez',NULL,'2500');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9913,'Kedungbanteng Krajan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2715,'El Alamo','Sonora','83448');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3996,'Santa Rosa',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4993,'Maglaj',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8861,'Dashiren',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8029,'Hyltebruk','Halland','314 32');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5984,'Agra','Braga','4705-653');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8997,'Huoshaoping',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8542,'Petaling Jaya','Selangor','46781');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3291,'Brondong',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (794,'Val-d''Or','Québec','J9P');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (138,'Estância',NULL,'49200-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7380,'Santa Cruz',NULL,'5105');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7120,'Chornoliztsi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7216,'Lokolande',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3818,'Cogon',NULL,'1686');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1540,'Lagos',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5862,'Jardin','Tamaulipas','87330');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1660,'Toamasina',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8114,'Zombo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9753,'Dolgoprudnyy',NULL,'141707');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7845,'Aswan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4839,'Curridabat',NULL,'11801');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (642,'Denver','Colorado','80204');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7523,'Rychvald',NULL,'735 32');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3501,'Las Palmas',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4947,'Skuhrov nad Bělou',NULL,'517 03');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2459,'Bilar',NULL,'6317');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4820,'Quebrada Larga',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (52,'Independencia','Chiapas','30815');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (109,'Archis',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (601,'Kohtla-Järve',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8598,'Orléans','Centre','45957 CEDEX 9');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3052,'Hanna','Alberta','T6L');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3617,'Bagalangit',NULL,'4203');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6319,'Ryūō',NULL,'407-0176');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8699,'Shatian',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4417,'Salt Lake City','Utah','84115');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9738,'Otok',NULL,'40323');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9471,'Hongtang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6369,'Loimaan Kunta',NULL,'32560');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4119,'Currais Novos',NULL,'59380-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3428,'Tanuma',NULL,'426-0061');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7350,'Yangju',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (758,'Balyaga',NULL,'673020');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8721,'Messina','Sicilia','98146');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1721,'Piripiri',NULL,'64260-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2760,'Thành Phố Thái Bình',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3930,'Bazar-Korgon',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8382,'Figueiredo','Braga','4705-722');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6384,'Kupahandap',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6854,'Barra Cheia','Setúbal','2860-205');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4142,'Dogarmo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3020,'Quankou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5627,'Koba',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8015,'Rudziczka',NULL,'43-267');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (651,'Cassanayan',NULL,'5018');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5701,'Quiches',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8331,'Nowe Miasto',NULL,'09-120');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1684,'Loštice',NULL,'789 83');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2303,'Kamuli',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5473,'Mestre','Veneto','30175');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8560,'Qingxi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7885,'Reutov',NULL,'143969');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3430,'Ranong',NULL,'85000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1540,'Ta’ Xbiex',NULL,'ZTN');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (796,'Labuhanlalar',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2968,'Cennan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9360,'Thành Phố Bà Rịa',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4847,'Arlington','Virginia','22217');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (649,'Lezhë',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3874,'La Falda',NULL,'4640');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2175,'Jinlong',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5799,'Niigata-shi',NULL,'951-8167');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9447,'Yukuriawat',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1709,'Norashen',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8060,'Le Mans','Pays de la Loire','72091 CEDEX 9');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4873,'Songgui',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8601,'Caibiran',NULL,'6548');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3757,'Visby','Gotland','621 85');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1468,'Euclides da Cunha',NULL,'48500-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (102,'Kayunga',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8920,'Bolaoit',NULL,'2422');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2334,'Javhlant',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (51,'Sel’tso',NULL,'241551');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9572,'Lukou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7824,'Pyatnitskoye',NULL,'309666');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9822,'Jatirejo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1033,'Valence','Rhône-Alpes','26029 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5042,'Besançon','Franche-Comté','25045 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1727,'General San Martín',NULL,'1702');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9799,'Sangiang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (169,'Camplong',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9261,'Bellavista',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9405,'Rivesaltes','Languedoc-Roussillon','66605 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1854,'Villa Urquiza',NULL,'4000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5397,'Cincinnati','Ohio','45208');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7275,'Cherskiy',NULL,'678831');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7711,'Jinniu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9368,'Ralung',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4474,'Severnyy',NULL,'346763');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3474,'Encrucijada',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5447,'Leifeng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (763,'Raphoe',NULL,'X91');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7669,'Zhushan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9696,'Stockholm','Stockholm','118 50');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1481,'Vân Tùng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8112,'Fengli',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2427,'Oetutulul',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6114,'Troyes','Champagne-Ardenne','10014 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9515,'Minante Segundo',NULL,'3306');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5832,'Bužim',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4769,'A dos Cunhados','Lisboa','2560-028');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5497,'Thung Yang Daeng',NULL,'46000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5447,'Passo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6709,'Andrijaševci',NULL,'32271');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3465,'Blachownia',NULL,'42-293');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9747,'Dongzhaogezhuang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7624,'Huagu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2114,'Donja Brela',NULL,'21322');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5828,'Bududa',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4414,'Quanshang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5652,'Ugljevik',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6028,'Sant Cugat Del Valles','Cataluna','08190');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3318,'Baleal','Leiria','2520-005');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6732,'San Francisco Zapotitlán',NULL,'10009');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8101,'Brodarica',NULL,'51242');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1025,'Pilar',NULL,'8420');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5219,'Blois','Centre','41015 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9701,'Cirahab',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8657,'Valence','Rhône-Alpes','26009 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9983,'Qunsheng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (948,'El Quetzal',NULL,'12020');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7205,'Tolstoy-Yurt',NULL,'366013');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (694,'Nürnberg','Bayern','90480');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4462,'Hat Yai',NULL,'90110');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7325,'Nickby',NULL,'21310');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8239,'Puerto Colombia',NULL,'941047');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3348,'Slavs’ke',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2913,'Culacling',NULL,'4409');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4677,'Solntsevo',NULL,'243429');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2960,'Ciepielów',NULL,'27-310');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6762,'Lampa',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3945,'Phanom Phrai',NULL,'24140');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3588,'Sampao',NULL,'8113');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9590,'Zanjān',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8786,'Karangwaru',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3893,'Loivos','Vila Real','5425-055');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8121,'Tambaksari',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9975,'Nifuboko',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8138,'Agbannawag',NULL,'5103');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1729,'El Coco',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4161,'Kham Sakae Saeng',NULL,'30290');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3056,'Algarvia','Ilha de São Miguel','9630-224');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (766,'Gaopeng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (907,'Skärhamn','Västra Götaland','471 31');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3807,'Garunggang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7945,'Tópaga',NULL,'152047');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5334,'Dolores',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5915,'Xuxiake',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7951,'Ed','Västra Götaland','668 92');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6968,'Guodu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8185,'Toledo','Ohio','43610');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6625,'Pasirmanggu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (470,'Krajan Baru',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (92,'Tchoban Bey',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (347,'Fukuoka-shi',NULL,'816-0097');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5660,'Yashio-shi',NULL,'341-0053');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5716,'Sakai',NULL,'999-2256');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3978,'Rimouski','Québec','G5N');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9912,'Orléans','Centre','45969 CEDEX 9');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3771,'Pleiku',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (494,'Kranjska Gora',NULL,'4280');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1883,'Sorang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9855,'Kislyakovskaya',NULL,'352020');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4364,'Shināş',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (605,'Al Fukhkhārī',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1997,'Waingapu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8653,'Áyios Vasílios',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8807,'Saronída',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2647,'Wilkes Barre','Pennsylvania','18706');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (313,'Bentar',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8927,'Piraquara',NULL,'83300-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5730,'Malusac',NULL,'2005');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7787,'Embajador Martini',NULL,'6203');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2001,'Skellefteå','Västerbotten','931 77');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7381,'Aix-en-Provence','Provence-Alpes-Côte d''Azur','13617 CEDEX 1');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7100,'Ash Shaykh Zuwayd',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (571,'Gatesville','Texas','76598');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1888,'Cala',NULL,'5455');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7981,'Comrat',NULL,'MD-5354');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8311,'Domaniewice',NULL,'99-434');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5877,'Oslo','Oslo','0915');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7930,'Lindome','Västra Götaland','437 92');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1883,'Nishinoomote',NULL,'891-3101');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7221,'Kombapari',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2044,'Pancheng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4477,'Xilu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3070,'Ambanja',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3029,'Tanahedang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8702,'Dūrā al Qar‘',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (143,'Aulnay-sous-Bois','Île-de-France','93604 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6663,'Sukaharja',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6783,'Sindou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9241,'Sulaco',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9917,'Pingshan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3523,'Maanĭt',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1305,'Le Bourget-du-Lac','Rhône-Alpes','73379 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1915,'Al Abyār',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (782,'Paraisópolis',NULL,'37660-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1478,'Ōmiya',NULL,'319-3117');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2557,'Talisayan',NULL,'9012');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (268,'Tangga',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8931,'Piedrancha',NULL,'525069');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8214,'Xiaohe',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4536,'Duszniki-Zdrój',NULL,'57-340');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2501,'Sieroszewice',NULL,'63-405');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3283,'Novocherkassk',NULL,'346408');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7126,'Aipe',NULL,'411008');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9783,'Dalazi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7494,'Iquipi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (220,'Górzno',NULL,'87-320');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3853,'Futian',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9012,'Betzdorf',NULL,'L-6832');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4349,'Tong’an',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9219,'Raków',NULL,'26-035');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (46,'Datong',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4250,'Lowayu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2983,'Shiozawa',NULL,'989-0842');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1218,'Runaway Bay',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2282,'Utan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7744,'Mar’ina Roshcha',NULL,'901993');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1690,'San Rafael','Guerrero','41640');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9371,'Tanjung Raja',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (22,'Ludishan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1592,'Wārāh',NULL,'77041');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3860,'Staronizhestebliyevskaya',NULL,'606231');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5098,'Mao',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1341,'Sukarame',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5652,'Kadubincarung',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7796,'Jiawu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5828,'Mirimire',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3254,'Axioúpoli',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2913,'Một Ngàn',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8739,'Seredyna-Buda',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1087,'Tumpukrenteng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3673,'Ningde',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7501,'Almafuerte',NULL,'3317');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8402,'Izyum',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7641,'Satipo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6007,'Kula',NULL,'3818');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4397,'Sibay',NULL,'453839');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8001,'Susoh',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3064,'Buzhakan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3332,'Luso','Aveiro','3050-225');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8498,'Nantes','Pays de la Loire','44094 CEDEX 1');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9867,'Bralin',NULL,'63-640');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2475,'Fullerton','California','92640');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4005,'Al ‘Ulá',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (924,'Peñal',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5142,'Rosthern','Saskatchewan','B0L');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9612,'Sumberdangdang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7171,'Cikadu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2606,'Dembeni',NULL,'97660');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8853,'Čortanovci',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4651,'Kutasari',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2506,'Purwosari',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9462,'Fusagasuga',NULL,'252219');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3521,'Dongtian',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4702,'Kolomak',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4982,'La Trinidad',NULL,'2601');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3578,'Itaporanga',NULL,'18480-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2937,'Shatou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5182,'Tembayangan Barat',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8048,'Acherítou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3932,'Ngadipuro',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6453,'Casal de Cambra','Lisboa','2605-006');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2163,'Lerum','Västra Götaland','443 33');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3489,'Uman’',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7147,'Mainque',NULL,'8326');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4319,'Novoaltaysk',NULL,'658089');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4170,'Voznesenskoye',NULL,'607340');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6616,'Banjar Swastika',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5158,'Rejanegara',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8947,'Fond du Sac',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9832,'Tianhe',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7001,'Panjāb',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9997,'Sioguí Abajo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5874,'Xiting',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7590,'Gus’-Khrustal’nyy',NULL,'601508');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7526,'Cacocum',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5556,'Wangmo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2292,'Horodnytsya',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9878,'Marne-la-Vallée','Île-de-France','77427 CEDEX 2');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4243,'Hanjia',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8241,'Tiassalé',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6138,'Åtvidaberg','Östergötland','597 50');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4127,'Anju',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9294,'Bigaan',NULL,'6105');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2087,'Baiguo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9396,'Pereiras','Porto','4620-073');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6713,'Yugang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4904,'Aloja',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7080,'Anadia','Aveiro','3780-204');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2900,'Soio',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (197,'Nowlamary',NULL,'3731');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3051,'Frankfort','Kentucky','40618');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (547,'Wangxian',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (603,'Xiagong',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7291,'Governador Valadares',NULL,'35000-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3955,'Almaznyy',NULL,'678181');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1202,'Arcos de Valdevez','Viana do Castelo','4970-434');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (451,'Rawasan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8016,'Sukabumi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8318,'Pliwetan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5062,'Lavia',NULL,'38601');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3646,'Andou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7674,'Zagnitkiv',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1490,'Lavras',NULL,'37200-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9932,'Susiec',NULL,'22-672');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2939,'Vokhaïkó',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2606,'Bunutan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4601,'Itapuranga',NULL,'76680-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8055,'Villefranche-sur-Mer','Provence-Alpes-Côte d''Azur','06239 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (474,'Weicheng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (693,'Njeru',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9026,'Altan-Ovoo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1671,'Bukal Sur',NULL,'4323');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (921,'Rousínov',NULL,'683 01');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8964,'Lisovi Sorochyntsi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (211,'Tô Hạp',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (897,'Sorang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2049,'Fumin',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (135,'Tianqian',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7472,'Ligang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4161,'Juradó',NULL,'276019');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8696,'Monastyrishche',NULL,'692380');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5141,'Sandefjord','Vestfold','3210');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3702,'Santa Anita','Guanajuato','38900');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6771,'Barranco de Loba',NULL,'133518');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (749,'Nagornyy',NULL,'142817');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6253,'Corrientes',NULL,'3400');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5664,'Nepalgunj',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8043,'Seremban','Negeri Sembilan','70504');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4941,'Santiago Puringla',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6788,'Balin',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9717,'Sagua de Tánamo',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (706,'East London',NULL,'5688');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8447,'Calle Blancos',NULL,'10803');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5750,'Paris 03','Île-de-France','75151 CEDEX 03');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6536,'Los Angeles','California','90030');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6961,'Berlin','Berlin','14109');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9446,'Bokat',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9374,'San Juan Sacatepéquez',NULL,'01059');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2817,'Stockholm','Stockholm','112 75');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4457,'Gusong',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7981,'Shiraoka',NULL,'349-0218');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7551,'Sangojar',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (496,'Cijeungjing Kaler',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1643,'Mekarjaya',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5275,'Pruszcz',NULL,'86-120');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8820,'Clearwater','Florida','34629');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7108,'Zhangbagou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3032,'Guangshun',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7643,'‘Awartā',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2616,'Yala',NULL,'95000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1034,'Trollhättan','Västra Götaland','461 25');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8151,'Arras','Nord-Pas-de-Calais','62004 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1421,'Hongshan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (302,'Banawang',NULL,'2107');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6195,'Guisijan',NULL,'5705');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5421,'Gosë e Madhe',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3033,'Dvinskoy',NULL,'165500');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4587,'Warburton',NULL,'39180');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9334,'Ordynskoye',NULL,'633260');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3462,'Shuangmiao',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (672,'Stockholm','Stockholm','114 79');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (636,'Rājo Khanāni',NULL,'72111');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5762,'Niimi',NULL,'718-0011');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (523,'Xinhe',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (505,'Nossa Senhora de Machede','Évora','7005-676');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3442,'Solomenskoye',NULL,'357937');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7051,'Xiabeisi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7170,'Stari Lec',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7004,'Groblersdal',NULL,'1064');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4769,'Bang Phae',NULL,'70160');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6960,'Lianzhu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6970,'Gaocheng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2028,'Xinhua',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4277,'Ruzhany',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (172,'Cruz de Pau','Setúbal','2845-005');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3088,'Pazin',NULL,'52000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2565,'Železná Ruda',NULL,'340 04');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6520,'Colosó',NULL,'707037');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6051,'Tsuruga',NULL,'957-0355');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3472,'Shiraoka',NULL,'349-0218');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1126,'Amsterdam Oud Zuid en Rivierenbuurt','Provincie Noord-Holland','1079');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1817,'Verba','Aveiro','3810-600');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9326,'Guling',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3306,'Cempa',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (658,'Rebrikha',NULL,'658540');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6708,'Ramat Yishay',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7784,'Lücheng',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9886,'Songgang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4647,'Uarini',NULL,'69485-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9363,'Badou',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2823,'Bolo',NULL,'4712');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8457,'Nyanga',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9669,'Tongouson',NULL,'7010');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3720,'Montpellier','Languedoc-Roussillon','34087 CEDEX 4');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9779,'Mufumbwe',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6468,'Granada',NULL,'252257');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (75,'Morro do Chapéu',NULL,'44850-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8933,'Melíssi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (612,'Caen','Basse-Normandie','14922 CEDEX 9');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5726,'Uacon',NULL,'1169');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2243,'Dois Córregos',NULL,'17300-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4324,'Forssa',NULL,'30421');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9774,'Krajan Dua Patempuran',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5553,'Penengahan',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (868,'Atiquizaya',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8544,'El Porvenir','Veracruz Llave','93816');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (809,'Símantra',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5468,'Virginia',NULL,'9484');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3519,'Haveliān',NULL,'22501');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7886,'Río Ceballos',NULL,'5113');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7430,'Chuntai',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1366,'Pocora',NULL,'70603');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5444,'Puntarenas',NULL,'60101');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7590,'Sampit',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5175,'Xuguang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (133,'Kagadi',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2732,'Radoboj',NULL,'49232');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2600,'Karlstad','Värmland','652 17');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3435,'Gaio','Setúbal','2860-613');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2183,'Siyang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2569,'Longmiao',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5785,'Telde','Canarias','35213');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4990,'Galaz',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (8774,'Jingyao',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9191,'Pavlivka',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3013,'Linstead',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4260,'Mora','Dalarna','792 92');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3534,'Jianshe',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3869,'Bilad',NULL,'6401');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4995,'Itaperuçu',NULL,'83560-000');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9952,'Malartic','Québec','X0G');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6209,'Ochota',NULL,'05-090');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3634,'Stockholm','Stockholm','115 77');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6783,'Chorotis',NULL,'3733');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5781,'Srubec',NULL,'370 06');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1546,'Chantilly','Picardie','60647 CEDEX');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (7672,'Ngluwuk',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1926,'Yingdianjie',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (2146,'Naguilian',NULL,'3303');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5850,'Kelmė',NULL,'86001');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9860,'Hamberang Sabrang',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3052,'Banyliv',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (6259,'Santa Brigida',NULL,'7209');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3104,'Pule',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5321,'Awgu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (9874,'Damu',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4816,'Langpas',NULL,'1053');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (3132,'Kaniów',NULL,'26-050');
INSERT INTO UserAddress(userid,city,state,zip) VALUES (5367,'Wates',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (1519,'Baluk',NULL,NULL);
INSERT INTO UserAddress(userid,city,state,zip) VALUES (4942,'Shimonoseki',NULL,'801-0885');